# Generated by Django 6.0.5 on 2026-05-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
    ]
