# Generated by Django 6.0.5 on 2026-05-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_address_student_batch_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhar_number',
            field=models.CharField(default='000000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='admission_year',
            field=models.CharField(default='2025', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(default='9999999999', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='prn_no',
            field=models.CharField(default='9999999999', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='9999999999', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='sr_no',
            field=models.IntegerField(default=0),
        ),
    ]
