# Generated by Django 6.0.5 on 2026-05-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_aadhar_number_student_admission_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobile_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('osac_id', models.CharField(max_length=100)),
                ('ug_experience', models.CharField(max_length=100)),
                ('pg_experience', models.CharField(max_length=100)),
                ('pg_passing_year', models.CharField(max_length=10)),
                ('aadhar_no', models.CharField(max_length=20)),
                ('pan_no', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=200)),
                ('joining_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
